user
  name: Mac
  email: maclong9@icloud.com
tools
  - common
   - golang
   - rust
   - nodejs
   - zig
  - computer
    - common
      - eww
      - julia
      - kitty
      - neovim
      - obs
      - orbstack
    - linux
      - hyprland
      - firefox
    - mac
      - brew
        - amethyst
        - was
      - mas
        - music tools
        - video tools
        - xcode
remove
  - mobile
    -
  - computer
    - common
      - .termux
    - linux
      - 
    - mac
      -
