tools
  - common
   - golang
   - rust
   - nodejs
   - zig
  - computer
    - common
      - eww
      - julia
      - kitty
      - neovim
      - obs
      - orbstack
    - linux
      - hyprland
      - firefox
    - mac
      - amethyst
