git:
  user:
    name: Mac
    email: maclong9@icloud.com
  push:
    autoSetupRemote: true
tools:
  all:
    packages:
      - bat
      - dust
      - eza
      - fd
      - gh
      - hyperfine
      - neovim
      - nodejs
      - perl
      - ripgrep
      - rust
      - starship
      - tealdeer
      - tokei
      - vim
      - zellij
      - zig
    zsh:
      packages:
        - atuin
        - zoxide
        - zsh
      plugins:
        - djui/alias-tips
        - jeffreytse/zsh-vi-mode
        - marlonrichert/zsh-autocomplete
        - zsh-users/zsh-autosuggestions
        - zsh-users/zsh-syntax-highlighting
        - hchbaw/zce.zsh
  mobile:
    packages:
      - ncurses-utils
      - openssh
  computer:
    all:
      packages:
       - julia
       - kitty
       - neovim
       - obs
       - orbstack
    linux:
      packages:
        - firefox
    mac:
      packages:
        - mas
    nonbrew:
      - hyprland
      - eww
  node:
    - bun
    - pnpm
    - vercel
