user:
  name: Mac
  email: maclong9@icloud.com
tools:
  common:
   - bat
   - dust
   - eza
   - fd
   - golang
   - hyperfine
   - nodejs
   - perl
   - rust
   - starship
   - tmux
   - tokei
   - vim
   - zig
   - zsh
  computer:
    common:
      - eww
      - eza
      - julia
      - kitty
      - neovim
      - obs
      - orbstack
    linux:
      - hyprland
      - firefox
    mac:
      brew:
        - amethyst
        - was
      mas:
        - music tools
        - video tools
        - xcode
remove:
  mobile:
    -
  computer:
    common:
      - 'rm -rf .termux'
      - 'exa'
    linux:
      - 
    mac:
      -
settings:
  mobile:
    -
  computer:
    common:
      -
    linux:
      - 
    mac:
      -
