user:
  name: Mac
  email: maclong9@icloud.com
tools:
  all:
    packages:
      - bat
      - dust
      - eza
      - fd
      - gh
      - golang
      - hyperfine
      - ncurses-utils
      - nodejs
      - openssh
      - perl
      - ripgrep
      - rust
      - starship
      - tealdeer
      - tokei
      - vim
      - zellij
      - zig
      - zoxide
      - zsh
    node:
      - pnpm
      - vercel
  computer:
    packages:
      - eww
      - julia
      - kitty
      - neovim
      - obs
      - orbstack
    node:
      - bun
    linux:
      - hyprland
      - firefox
    mac:
      brew:
        - amethyst
        - mas
      mas:
        - music tools
        - video tools
        - xcode
