user:
  name: Mac
  email: maclong9@icloud.com
tools:
  common:
   - bat
   - dust
   - eza
   - fd
   - gh
   - golang
   - hyperfine
   - ncurses-utils
   - nodejs
   - perl
   - rust
   - starship
   - tealdeer
   - tmux
   - tokei
   - vim
   - zig
   - zoxide
   - zsh
  computer:
    common:
      - eww
      - julia
      - kitty
      - neovim
      - obs
      - orbstack
    linux:
      - hyprland
      - firefox
    mac:
      brew:
        - amethyst
        - mas
      mas:
        - music tools
        - video tools
        - xcode
