syntax on
set nu nowrap nocompatible shiftwidth=2 tabstop=2
autocmd BufRead,BufNewFile *.md set wrap
filetype plugin on

no s <Plug>(easymotion-overwin-f) 
no f :Files<cr>
no Q :q<cr>
no W :w<cr> 
noremap h h
noremap t j
noremap n k
noremap s l
noremap l n
noremap L N
noremap - $
noremap _ ^

let g:user_emmet_leader_key=','

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif
  
call plug#begin()
 Plug 'easymotion/vim-easymotion'
 Plug 'github/copilot.vim'
 Plug 'jiangmiao/auto-pairs'
 Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
 Plug 'junegunn/fzf.vim'
 Plug 'junegunn/vim-plug'
 Plug 'mattn/emmet-vim'
 Plug 'sheerun/vim-polyglot'
 Plug 'vimwiki/vimwiki'
call plug#end()
