syntax on
set nu nowrap nocompatible shiftwidth=2 tabstop=2
autocmd BufRead,BufNewFile *.md set wrap
filetype plugin on

nmap s <Plug>(easymotion-overwin-f) 
nmap f :Files<cr>
nmap Q :q<cr>
nmap W :w<cr> 

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif
  
call plug#begin()
 Plug 'easymotion/vim-easymotion'
 Plug 'github/copilot.vim'
 Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
 Plug 'junegunn/fzf.vim'
 Plug 'junegunn/vim-plug'
 Plug 'sheerun/vim-polyglot'
 Plug 'vimwiki/vimwiki'
call plug#end()
