syntax on
set nu nowrap nocompatible shiftwidth=2 tabstop=2
autocmd BufRead,BufNewFile *.md set wrap
filetype plugin on

no h h
no t j
no n k
no s l
no l n
no L N
no - $
no _ ^
no S <Plug>(easymotion-overwin-f) 
no <expr> f (len(system('git rev-parse')) ? ':Files' : ':GFiles --exclude-standard --others --cached')."\<cr>"
no Q :q<cr>
no W :w<cr> 

let g:user_emmet_leader_key=','

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif
  
call plug#begin()
 Plug 'easymotion/vim-easymotion'
 Plug 'github/copilot.vim'
 Plug 'jiangmiao/auto-pairs'
 Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
 Plug 'junegunn/fzf.vim'
 Plug 'junegunn/vim-plug'
 Plug 'mattn/emmet-vim'
 Plug 'sheerun/vim-polyglot'
 Plug 'vimwiki/vimwiki'
call plug#end()
