github.com:
    users:
        mac-codes9:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: mac-codes9
