github.com:
    users:
        mac-codes9:
            oauth_token: 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
    git_protocol: https
    user: mac-codes9
    oauth_token: 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
