github.com:
    users:
        mac-codes9:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: mac-codes9
