eval "$(starship init zsh)"
eval "$(atuin init zsh)"
eval "$(zoxide init zsh)"

source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/functions.zsh
source ~/.zplug/init.zsh

zplug "jkcdarunday/zplug-blame"
zplug "MichaelAquilina/zsh-you-should-use"
zplug "jeffreytse/zsh-vi-mode"
zplug "marlonrichert/zsh-autocomplete"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zplug/zplug", hook-build:"zplug --self-manage"
zplug check || zplug install
zplug clean && zplug update && zplug load
